spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myapp
    username: root
    password:
    #type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      suffix: .html
      prefix: /
servlet:
  multipart:
    enabled: true
#  mvc:
#    static-path-pattern=/static/**:
#mybatis:
#映射文件放在resources文件目录下
#  mapper-locations: classpath:/mapper/*.xml

